<?php

echo "<h1>Hello World</h1>";

echo PHP_EOL;?>
<div class="d-inline p-2 bg-dark text-white">
<?php echo $this->tag->linkTo(
    'productadd/products',
    'Add Product Here!'
);

?>
</div>
<div class="d-inline p-2 bg-dark text-white">
<?php echo $this->tag->linkTo(
    'productslist/productlist',
    'Product Table Is Here!'
);

?>
</div>
<div class="d-inline p-2 bg-dark text-white">
<?php echo $this->tag->linkTo(
    'orderadd/orders',
    'Orders Add Here!'
);

?>
</div>
<div class="d-inline p-2 bg-dark text-white">
<?php echo $this->tag->linkTo(
    'orderslist/orderlist',
    'Order Table Is Here!'
);

?>
</div>
<div class="d-inline p-2 bg-dark text-white">
<?php echo $this->tag->linkTo(
    'settings/setting',
    'Settings!'
);

?>
</div>
