<h2>Sign Up </h2>
<div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
    <?php echo isset($message)?$message:''; ?>
</div>

<?php echo $this->tag->form("signup/signup"); ?>
<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>
<p>
    <label for="email">email</label>
    <?php echo $this->tag->textField("email"); ?>
</p>
<p>
    <label for="password">password</label>
    <?php echo $this->tag->textField("password"); ?>
</p>
<p>
    <div for="drop-down">
        <label for="name">Choose a role:</label>
        <select for="role" name="role">
            <?php echo $options; ?>
        </select>
    </div>
    
</p>
<?php echo $this->tag->submitButton("Submit"); ?>
</form>